spring.application.name=medical-clinic-proxy
server.port=8080
# --- medical-clinic address
medical-clinic.api.url=${MEDICAL_CLINIC_URL:http://localhost:8081}
# --- Feign ---
spring.cloud.openfeign.circuitbreaker.enabled=false
spring.cloud.openfeign.client.config.medical-clinic.connect-timeout=2000
spring.cloud.openfeign.client.config.medical-clinic.read-timeout=3000
spring.cloud.openfeign.client.config.medical-clinic.logger-level=basic
# --- logi ---
logging.level.com.example.medicalclinicproxy.client=DEBUG
# --- Resilience4j ---
resilience4j.circuitbreaker.instances.medical-clinic.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.medical-clinic.sliding-window-size=20
resilience4j.circuitbreaker.instances.medical-clinic.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.medical-clinic.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.medical-clinic.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.medical-clinic.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.medical-clinic.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.medical-clinic.slow-call-rate-threshold=60
resilience4j.circuitbreaker.instances.medical-clinic.slow-call-duration-threshold=3s
resilience4j.circuitbreaker.instances.medical-clinic.ignore-exceptions[0]=com.example.medicalclinicproxy.exceptions.ResourceNotFoundException
resilience4j.circuitbreaker.instances.medical-clinic.ignore-exceptions[1]=com.example.medicalclinicproxy.exceptions.MedicalClinicConflictException
resilience4j.circuitbreaker.instances.medical-clinic.ignore-exceptions[2]=com.example.medicalclinicproxy.exceptions.MedicalClinicProxyBadRequestException